# Generated by Django 2.0.13 on 2019-12-29 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('name_kor', models.CharField(max_length=50)),
                ('name_eng', models.CharField(max_length=50)),
                ('price_sale', models.IntegerField(default=0)),
                ('price_order', models.IntegerField(default=0)),
                ('delivery_price', models.IntegerField(default=0)),
                ('delivery_send', models.CharField(max_length=100)),
                ('delivery_return', models.CharField(max_length=100)),
                ('company_make', models.CharField(max_length=20)),
                ('company_sale', models.CharField(max_length=20)),
                ('company_as', models.CharField(max_length=20)),
            ],
        ),
    ]
