# Generated by Django 2.0.13 on 2019-12-29 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='model',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
