# Generated by Django 2.0.13 on 2019-12-29 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20191229_0336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='model',
        ),
        migrations.AddField(
            model_name='listing',
            name='name_model',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
