# Generated by Django 2.0.13 on 2019-12-29 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_auto_20191229_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='name_model',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
