# Generated by Django 2.0.13 on 2020-01-03 14:53

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_auto_20191229_0343'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='inform',
            field=models.TextField(default=builtins.dir),
            preserve_default=False,
        ),
    ]
