# Generated by Django 2.0.13 on 2020-02-15 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cont',
            name='article',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
